CREATE TABLE IF NOT EXISTS "campaign" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	"last_phone_id"	INTEGER NOT NULL DEFAULT 0,
	"total_imported"	INTEGER NOT NULL DEFAULT 0,
	"total_called"	INTEGER NOT NULL DEFAULT 0,
	"total_fail"	INTEGER DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "campaign_data" (
	"id"	INTEGER NOT NULL,
	"campaign_id"	INTEGER NOT NULL,
	"phone"	TEXT NOT NULL,
	"call_state"	INTEGER NOT NULL DEFAULT 'NOT_CALL',
	"index"	INTEGER NOT NULL DEFAULT 0,
	"is_called"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);